### ISSUE TITLE
Filestore: удаление файлов

### ISSUE THREAD

**Issue by ridouchire** [U-Me-Chan/umechan#12]
Для нужд администрирования добавить возможность удалять файлы. Удаление - это фактически замена оригинального изображения и его миниатюры на некую плашку "Файл удалён".

Также при удалении поста автором - удалять вместе с этим и все файлы, прикреплённые к посту.

Удаление выполняется с помощью указанного в окружении ключа администратора.

**Comment by ridouchire** [comment]
Ещё неплохо при удалении поста взять и удалить все файлы, связаные с ним.

**Comment by Oxore** [comment]
> Ещё неплохо при удалении поста взять и удалить все файлы, связаные с ним.

Тогда стоит находить все посты, ссылающиеся на те же файлы и если такие посты найдены, то не удалять эти файлы. Это будет особенно актуально, если в файлсторе будет реализована дедупликация.

**Comment by ridouchire** [comment]
Наврядли я буду во время удаления файла проверять, ссылается ли кто-то ещё на него. Слишком трудозатратно, да и зачем?

**Comment by Oxore** [comment]
В смысле зачем? Ну вот тебе кейс: я - аватарка, использую одну и ту же комбинацию thumbnail+image в виде заготовленной markdown конструкции, втыкаю её везде, почти в каждый свой пост. Потом решаю исправить опечатку в недавнем своём посте, удаляю его, чтобы перезапостить, а пикча с файлстора тоже удаляется автоматически и вуаля - все мои аватарки на всех моих постах пропадают, потому что файл от последнего моего поста удалён автоматически вместе с постом.

Второй кейс касается дедупликации, но он по сути такой же. Если дедупликация в файлсторе будет когда-либо реализована и реализована она будет, допустим, как на catbox.moe, то повторная загрузка такой же картинки, которая была загружена ранее, вернёт каждый раз тот же самый старый URL от первой загрузки. Тогда при удалении одного поста с этой картинкой удалятся все посты, что неожиданно и нежелательно.

**Comment by Oxore** [comment]
Так, я немного потерял контекст в своих рассказах.

> Для нужд администрирования добавить возможность удалять файлы.

Если это касается только администрирования, то здесь ситуация немного другая, я в ней не шарю. Извините за беспокойство. Всего доброго.
