### ISSUE TITLE
Filestore: при постинге 404, если стоит завершающий слеш

### ISSUE THREAD

**Issue by Oxore** [U-Me-Chan/umechan#13]
Если в конце пути, по которому отправляется POST запрос, находится слеш, то сервер возвращает 404 "not found". Вот пример:

```
 /tmp $ curl -F "=@a.jpg" http://scheoble.xyz/filestore
{
    "original_file": "http://scheoble.xyz/files/639a23b093013.jpg",
    "thumbnail_file": "http://scheoble.xyz/files/thumb.639a23b093013.jpg"
}%
 /tmp $ curl -F "=@a.jpg" http://scheoble.xyz/filestore/
not found%
```

Хотелось бы, чтобы при наличии завершающего слеша постинг тоже происходил без проблем.

Если вопрос принципиальный, то я готов отступиться и мы просто закроем этот issue.

**Comment by ridouchire** [comment]
@Oxore, я зафиксил проблему в зависимостях файлстора, и теперь должно работать в обоих случаях - с завершающим слешем, без него. Проверь, пожалуйста - я уже обновил файлстор на продакшн-сервере.

**Comment by Oxore** [comment]
@ridouchire Проблема никуда не делась, всё ещё возвращает not found вместо ссылок:

```
 /tmp $ curl -F "=@a.jpg" https://scheoble.xyz/filestore/
not found%
 /tmp $ curl -F "=@a.jpg" https://scheoble.xyz/filestore
{
    "original_file": "https://scheoble.xyz/files/63d557d337c12.jpg",
    "thumbnail_file": "https://scheoble.xyz/files/thumb.63d557d337c12.jpg"
}%
```

Но зато теперь стало обязательно постить через https, потому что при попытке запостить через http в ответ возвращается редирект на https версию.

**Comment by ridouchire** [comment]
И правда, чото в контейнере файлстора не было обновлённой версии. Пнул обновление зависимостей, проверил на проде - работает. Жду тестов от тебя.

**Comment by ridouchire** [comment]
@Oxore, алло!

**Comment by Oxore** [comment]
Блять, я сдох

**Comment by Oxore** [comment]
Потом

**Comment by Oxore** [comment]
Проверили с @ridouchire, всё ок, всё хорошо, давайте закрывать.
